# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "AnsibleControlNode" do |control|
    control.vm.box = "ubuntu/trusty64"
    control.vm.hostname = "control.example.com"
    control.vm.network "private_network", ip: "192.168.56.1"
    control.vm.provider "virtualbox" do |v|
      v.name = "AnsibleControlNode"
    end
  end

  config.vm.define "AnsibleManagedNode" do |host|
    host.vm.box = "ubuntu/trusty64"
    host.vm.hostname = "host.example.com"
    host.vm.network "private_network", ip: "192.168.56.2"
    host.vm.provider "virtualbox" do |v|
      v.name = "AnsibleManagedNode"
    end
  end



end
